[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]   


[dependencies]
cmake = "*"
ninja = "*"
eigen = "3.4.*"
benchmark = "1.9.*"
pcl = "1.15.*"
open3d = "0.19.*"


[package]
name = "cpp_robotics_algorithms"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
env = { CMAKE_VERBOSE_MAKEFILE = "ON", CXXFLAGS = "-O3 -march=native" }